/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.jzdayz.app;

import org.junit.jupiter.api.Test;

public class MessageUtilsTest {

  @Test
  public void testGetMessage() {
    assertEquals("Hello      World!", MessageUtils.getMessage());
  }
}
